### PR TITLE
First Derivative Plots Not Displayed After Checking "Show Derivative" in Analysis Tab #198

### LINKED ISSUE #198: First Derivative Plots Not Displayed After Checking "Show Derivative" in Analysis Tab
First Derivative Plots Not Displayed After Checking "Show Derivative" in Analysis Tab

Basic Summary
In the Analysis tab, when the checkbox titled "Show derivative" is selected, the first derivative plots are not being displayed. This issue prevents users from visualizing the derivative plots, which are crucial for certain analyses.

What Must Be Changed
Investigate and resolve the issue where the first derivative plots are not rendered when the "Show derivative" checkbox is checked.
Ensure that the derivative plots are correctly generated and displayed when the checkbox is selected.
Verify that no other functionalities are affected by this change.

Expected Outcome
Once the issue is resolved, the first derivative plots should be visible in the Analysis tab whenever the "Show derivative" checkbox is selected. Users should be able to view and interact with the derivative plots without encountering errors.

Acceptance Criteria

- [ ] Derivative Plot Rendering- The first derivative plots should be displayed immediately upon selecting the "Show derivative" checkbox.
- [ ] Checkbox Functionality- Ensure that checking and unchecking the "Show derivative" box toggles the display of the derivative plots as expected.
- [ ] No Impact on Other Features- The fix should not interfere with other functionalities in the Analysis tab or elsewhere in the software.

Subtasks

- [ ] Provide detailed analysis and debugging logic, and suggestions for fixes
- [ ] Derivative Plot Rendering

### PR DESCRIPTION
**Pull request by srepalli3**
Fixes #198

**What was changed?**

Added checkboxInput to ui.r to create a button to show derivatives, adjusted the conditional check for rendering derivative plots to use input$showDerivative instead of input[[paste0("firstDerivative", myI)]]. 

**Why was it changed?**

For ui.r: to ensure that the show derivative button is shown in the sidebar
for server.r: to ensures that when the checkbox is checked, the derivative plots are added to the plot.

**How was it changed?**
by adding snippets of code to ui.r and server. r, to ensure that the derivatives for the first two samples are shown

- added a specific button to show derivatives, but server.r changes weren't pushed because when testing, program did not work. 
- 
image
trying to make changes to this section^ 

**How was it tested**
Ran MeltShiny command to see if the derivative plots were being displayed for Samples 1 and 2.

### CODE REVIEW

**Comment by avazzano7** [comment]
Seems like a fairly large issue. Maybe this should be split into multiple smaller issues so progress can be made by multiple people?

**Comment by avazzano7** [comment]
Seems like a large issue, but this one's important for the end-goal. Maybe this should be split into multiple smaller issues so progress can be made by multiple people?

**Comment by Massi-Papi** [comment]
So, you just added another box called "Analysis Options" with a "Show derivative" checkbox.

Screenshot 2024-10-15 at 4 15 53 PM

Once you click on the checkbox, no derivative is shown. 
The issue is the first couple of samples are not showing the derivative. 
Look at the code base in the following areas and see how the derivative function is used and displayed. 
Looking at these sections of code might help:

_Server.r_: Lines 345-391
_global.r_: Line 116-121 & Line 127

**Comment by BollepalliPranitha** [comment]
@srepalli3 When I tried it with sample 2 
Sample 2
BLYA-1.1_MeltR.csv
No Blanks
Wavelength – 260
Nucleic acid type – RNA
Sequence – CCACGUCUCG,CGAGAGUGG
Molecular state - Heteroduplex
I was able to get derivates for sample 2 but not sample 1.
image

If possible please check and compare them

**Comment by BollepalliPranitha** [comment]
closing this PR as this issue is being handled by other PRs

**Pull request closed without merging**
