### PR TITLE
Enable Reset Option for Dataset Upload #195

### LINKED ISSUE #195: Enable Reset Option for Dataset Upload
Currently, in the File section, after browsing and uploading a dataset, users can perform the analysis. However, there is no option to upload another dataset, as the system doesn't allow resetting the previous file and re-uploading. To enhance user flexibility, a reset option must be implemented to clear the current dataset and allow users to upload a new one.

**What Must Be Changed:**
The reset functionality should be enabled after a dataset is uploaded. This reset option will allow users to clear all current data, results, and analysis, enabling them to browse and upload a new dataset.
Ensure the reset button is visible and functional after any dataset is added.

**Expected Outcome:**
Once the reset option is activated, users should be able to remove the current dataset and clear all analysis results. This will enable them to upload a new dataset for analysis without needing to refresh or reload the entire page.

**Acceptance Criteria**

- [ ] Reset Button Visibility: The reset button must be enabled and visible after a dataset is uploaded. The button should be located near the browse/upload file button.
- [ ] Full Data Clearance: Clicking the reset button should clear the entire dataset, analysis results, and any other associated data from the session. Users should be able to perform a new upload after using the reset button without reloading the page.
- [ ] File Upload Re-enable: After reset, the browse button should return to its original state, allowing users to add a new dataset for analysis.

### PR DESCRIPTION
**Pull request by srepalli3**
Fixes #195

**What was changed?**

I added a reset button to the main page that shows up after an initial upload of data to reset all inputs

**Why was it changed?**

This allows users to reset all inputs and plug in new data/datasets

**How was it changed?**
I added to ui.r to create the reset button and created the logic behind it in server.r. Mainly added "update____" to reset all other inputs to their default values and "enable" functions to reenable all inputs

**How was it tested**

After saving code, I ran the meltShiny command to see if the reset button showed up and if it reset all values when clicked.

**Screenshots that show the changes (if applicable):**
After Uploading Data: 
image
After clicking Reset Button:
image

### CODE REVIEW

**Review by avazzano7 — DISMISSED** [review]
Reset button code looks good!

**Comment by kate-holdener** [comment]
It's good to leave 'good first issue' for new developers. The team should focus on the more challenging core project issues.

**Comment by Massi-Papi** [comment]
@srepalli3 After clicking the "Reset Data" button, I am not able to reupload a data set file; After resetting, I click on "Browse," and nothing happens. 
Also, after clicking the reset button, I still see the data on the right hand side. 
Maybe rework the logic so that when the button is clicked the page "refreshes" and starts from scratch that way you don't have to hard code the reset values in the server logic.

**Comment by srepalli3** [comment]
This should work now, I completely overcomplicated it

**Comment by Massi-Papi** [comment]
> This should work now, I completely overcomplicated it

No worries! You figured it out! Nice work !

**Review by Massi-Papi — APPROVED** [review]

**Review by BollepalliPranitha — CHANGES_REQUESTED** [review]

**Review by BollepalliPranitha — CHANGES_REQUESTED** [review]
image
I was unable to get the derivatives.

**Comment by kate-holdener** [comment]
> image I was unable to get the derivatives.

@BollepalliPranitha I thought the derivatives issue was being tracked/worked on separately (PR #199 )

**Comment by BollepalliPranitha** [comment]
@kate-holdener Derivates worked for all the samples other than sample 1 and sample 2 before. Now I was unable to extract the derivates for any sample with this change.

**Comment by srepalli3** [comment]
i think i might have mixed up my branches by accident but the issue is fixed now. the derivative plots are showing up now with the change for the reset button.

**Comment by kate-holdener** [comment]
> @kate-holdener Derivates worked for all the samples other than sample 1 and sample 2 before. Now I was unable to extract the derivates for any sample with this change.

Thank you! Good catch.

**Pull request merged**
