### PR TITLE
Resolve Bug Causing Internal Errors with New Data Format (AYGU-1_MeltR)

### PR DESCRIPTION
**Pull request by adhampton110**
Fixes [181](https://github.com/oss-slu/MeltShiny/issues/181)

**What was changed?**

I revised the parsing logic in `server.r` to comply with MeltR's expected dataset format for files that have the same structure as `AYGU-1_MeltR`.

**Why was it changed?**

As stated in the user story, going forward, user input data will be structured like `AYGU-1MeltR.csv`. The current code strictly supports input files structured like `test.csv`. My code now supports input files structured like `AYGU-1_MeltR.csv`, instead of input file structured like `test.csv`. 

**How was it changed?**

The new input file standard, `AYGU-1MeltR.csv`, already complies with MeltR, almost. I have added one line that manipulates the data before it interacts with MeltR: `data <- raw_data %>% arrange(Sample)`. This line sorts the input data by the Sample column from lowest to highest (1,2,3,4,...).

Additionally the assignment of `numSamples` has been changed from `NULL` to `0`. This was done because the following would occur: 
```
9 + NULL = numeric(0). 
# problematic because we are unable to use the varaible later on to iterate during the creation of samples. 
```

**Screenshots that show the changes (if applicable):**

Each of the following cases were testing with the following configuration:
-  `AYGU-1MeltR.csv` input file
- No Blank
- 260 Wavelength
- 90 Temp
- RNA NucAcid
- CGAAAGGU,ACCUUUCG Sequence
- Nucleic Acid Sequence Molar Extinction Coeff.
- Methods 2 & 3 Enabled
- nls Tm method
- Heteroduplex molecular state

### Showcase of  `AYGU-1_MeltR.csv` Uploaded
image

### Showcase of Best Fit & Derivative Plots for Sample 3
image

### Showcase of Vant Hoff
image

### Showcase of Table
image

### Showcase of  `AYGU-1_MeltR.csv` Uploaded
Screenshot 2024-05-31 at 1 54 12 AM

### Showcase of Best Fit & Derivative Plots for Sample 3
Screenshot 2024-05-31 at 1 54 32 AM

### Showcase of Vant Hoff
Screenshot 2024-05-31 at 1 54 53 AM

### Showcase of Table
Screenshot 2024-05-31 at 1 55 12 AM

### CODE REVIEW

**Comment by Massi-Papi** [comment]
Wow!! Great work!! @adhampton110

**Comment by Massi-Papi** [comment]
Hey @adhampton110,

Let me reiterate, amazing work! 
However, there is one small problem; whenever I input the RNA sequence that we've been given, it grays out my screen once it is done processing after clicking, "Upload Data." 
Screenshot 2024-09-05 at 6 12 03 PM


As seen below, whenever I input a single RNA strand, it does work.

Screenshot 2024-09-05 at 6 14 58 PM
Screenshot 2024-09-05 at 6 15 45 PM

So for some reason, whenever it is multiple strands, it is not working on my local machine. 

I am using MacOS R version 4.3.1

**Comment by adhampton110** [comment]
@Massi-Papi Do you receive a console error that I could take a look at?

**Comment by Massi-Papi** [comment]
@adhampton110 

I'll post the warnings printed in the log:

[2024-09-06 11:32:08] | INFO | CREATING MELTR OBJECT 
**Warning: Error in round: non-numeric argument to mathematical function**
88: data.frame
87: meltR.A
84: myConnecter$constructObject [global.R#81]
....
[2024-09-06 11:32:08] | INFO | PROCESSING COMPLETE 
[2024-09-06 11:32:08] | INFO | ANALYSIS PLOTS RENDERED
...  
**Warning: Error in character: invalid 'length' argument**

**Comment by adhampton110** [comment]
@Massi-Papi Were you provided testing inputs for `AYGU-1_MeltR.csv`? Do you happen to know if they are the exact same as `test.csv`?

**Pull request merged**
